### ISSUE TITLE
Request: clear/reset log button

### ISSUE THREAD

**Issue by redfoxhub** [Yenof/chat-panel#2]
Would it be possible to add a button to clear or reset the currently selected log?

Nice plugin, thank you.

**Comment by Yenof** [comment]
Hi, thank you for the kind words. 

Currently if you toggle the plugin on and off it will clear the history, but if you would like to be able to reset a single tab's history and leave the other tabs with their history intact, I think I can do that.

Looking at making it so clicking the middle mouse button on the tab's name will reset it's history. 
Does that sound like an acceptable solution? This would be outlined in the readme if added.

Cool request, thank you. :D

**Comment by Yenof** [comment]
This feature will be added in [v1.4](https://github.com/runelite/plugin-hub/pull/5502). "Click tab name with MMB to clear tab history."

I used the middle mouse button (click scroll wheel) for this feature because left click is used to select tabs and right click has a planned use in the future. Without also adding a listener for keypresses, this seems like the best solution at the time. 

Not all devices have a MMB, but it looks like through touchpad software and/or AHK that it should still be accessible to most people.

I might want to have clear history added to a hypothetical right click (on tab) menu in the future. 

Feature added, closing issue, thank you for the new feature! :D

**Comment by Yenof** [comment]
Lol, already changed MMB to now be the right click menu I was hypothesizing. Here is a preview of how it should look in upcoming update. :)
![Screenshot from 2024-02-12 17-22-18](https://github.com/Yenof/chat-panel/assets/122739279/6740c5b0-fd6f-40d0-9789-1bb59a37be52)
